### ISSUE TITLE
9to10 - coreupgrader:upgrade

### ISSUE THREAD

**Issue by kszymukowicz** [ElementareTeilchen/upgrader#1]
hi

Many tanks for this packages and good inspirations.

I have a small question to https://github.com/ElementareTeilchen/upgrader/blob/main/9to10/migrate.sh

Do I get it right that if I am uprading 9 to 10 then instead of `${TYPO3_CONSOLE_BIN}  coreupgrader:upgrade` I can run just `${TYPO3_CONSOLE_BIN} upgrade:run all --no-interaction --confirm all`.

I assume running `${TYPO3_CONSOLE_BIN}  coreupgrader:upgrade`  would be good if the TYPO3 9 was upgraded in past from 8 and there were some undone upgraders yet?

**Comment by franzkugelmann** [comment]
Hi @kszymukowicz, yes you are right!
For a project which started with v9 it should be fine if you just run the regular upgrade wizards delivered with v10 Core.

**Comment by kszymukowicz** [comment]
tnx!
